"""Create_models

Revision ID: 026f789af3eb
Revises: 
Create Date: 2024-02-16 20:11:31.814557

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '026f789af3eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cars',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('number', sa.String(length=16), nullable=False),
        sa.Column('image', sa.String(length=256), nullable=True),
        sa.Column(
            'brand', sa.Enum(
                'toyota', 'honda', 'ford', 'bmw', 'mercedes_benz', 'volkswagen', 'nissan', 'hyundai', 'audi', 'subaru',
                'kia', 'tesla', 'mazda', name='brands'
                ), nullable=False
            ),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.Column(
            'transmission', sa.Enum('manual', 'automatic', 'automated_manual', 'hydrostatic', name='transmissions'),
            nullable=False
            ),
        sa.Column(
            'fuel_type',
            sa.Enum('gasoline', 'diesel', 'electric', 'hybrid', 'natural_gas', 'ethanol', name='fueltypes'),
            nullable=False
            ),
        sa.Column(
            'color', sa.Enum('white', 'black', 'silver', 'gray', 'blue', 'brown', 'gold', 'bronze', name='colors'),
            nullable=False
            ),
        sa.Column(
            'category', sa.Enum(
                'economy', 'compact', 'suv', 'crossover', 'luxury', 'sports', 'convertible', 'minivan', 'pickup_truck',
                name='categories'
                ), nullable=False
            ),
        sa.Column('engine_capacity', sa.Float(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('ordered', 'repaired', 'free', name='statuses'), nullable=False),
        sa.Column('station_id', sa.Integer(), nullable=False),
        sa.Column('cost_per_day', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('image'),
        sa.UniqueConstraint('number')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
