"""Create table

Revision ID: 7742258a359a
Revises: 
Create Date: 2023-10-12 21:42:03.132774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7742258a359a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.Enum('toyota', 'honda', 'ford', 'bmw', 'mercedes_benz', 'volkswagen', 'nissan', 'hyundai', 'audi', 'subaru', 'kia', 'tesla', 'mazda', name='brands'), nullable=False),
    sa.Column('transmission', sa.Enum('manual', 'automatic', 'automated_manual', 'hydrostatic', name='transmissions'), nullable=False),
    sa.Column('fuel_type', sa.Enum('gasoline', 'diesel', 'electric', 'hybrid', 'natural_gas', 'ethanol', name='fueltypes'), nullable=False),
    sa.Column('color', sa.Enum('white', 'black', 'silver', 'gray', 'blue', 'brown', 'gold', 'bronze', name='colors'), nullable=False),
    sa.Column('category', sa.Enum('economy', 'compact', 'suv', 'crossover', 'luxury', 'sports', 'convertible', 'minivan', 'pickup_truck', name='categories'), nullable=False),
    sa.Column('engine_capacity', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cost_per_day', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
