version: '3.7'


services:
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: beanie
      MONGODB_PASSWORD: beanie
      MONGODB_ROOT_PASSWORD: beanie
      MONGODB_DATABASE: orders_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
    mongodb_data:
