version: '3.7'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    user: root
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - dynamodb-data:/data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: dynamodb-local:8000
    depends_on:
      - dynamodb-local
    restart: always


volumes:
  dynamodb-data:
